name: main
on: push

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: test get-count-function
        run: cd get-function && python app.py -v ./ && cd ../../
      - name: test put-count-function
        run: cd put-function && python app.py -v ./ && cd ../../